version: "3"

services:
  postgres:
    image: locust-timescale
    networks:
      - timenet
    expose:
      - 5432
    ports:
      # remove the 127.0.0.1 to expose postgres to other machines (including load gen workers outside this machine)
      - 127.0.0.1:5432:5432
    environment:
      # change the password if you intend to expose postgres to other machines
      - POSTGRES_PASSWORD=password
      - TIMESCALEDB_TELEMETRY=off

networks:
  timenet: null
