[tool.ruff]
target-version = "py311"
line-length = 120
lint.ignore = ["E402", "E501", "E713", "E731"]
lint.select = ["E", "F", "W", "UP", "I001"]

[tool.ruff.lint.isort]
section-order = ["future", "locust_cloud", "standard-library", "third-party", "first-party", "local-folder"]

[tool.ruff.lint.isort.sections]
locust_cloud = ["locust_cloud"]

[tool.mypy]
# missing type stubs
ignore_missing_imports = true
python_version = "3.11"
