apiVersion: apps/v1
kind: Deployment
metadata:
  generateName: locust-master-
  labels:
    name: locust-master
    created-by: "locust-cloud-deploy"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: locust-master
  template:
    metadata:
      labels:
        app: locust-master
    spec:
      containers:
        - name: locust-master
          image: locustio/locust
          env:
            - name: LOCUST_MODE_MASTER
              value: "1"
            - name: LOCUST_LOGLEVEL
              value: debug
            - name: LOCUST_LOCUSTFILE
              value: https://raw.githubusercontent.com/locustio/locust/master/examples/basic.py
          ports:
            - name: loc-master-web
              containerPort: 8089
              protocol: TCP
            - name: loc-master-p1
              containerPort: 5557
              protocol: TCP
            - name: loc-master-p2
              containerPort: 5558
              protocol: TCP
