kind: Service
apiVersion: v1
metadata:
  generateName: locust-master-
  labels:
    app: locust-master
    created-by: "locust-cloud-deploy"
spec:
  ports:
    - port: 5557
      targetPort: loc-master-p1
      protocol: TCP
      name: loc-master-p1
    - port: 5558
      targetPort: loc-master-p2
      protocol: TCP
      name: loc-master-p2
  selector:
    app: locust-master

---
kind: Service
apiVersion: v1
metadata:
  generateName: locust-master-ui-
  labels:
    app: locust-master
spec:
  ports:
    - port: 8089
      targetPort: loc-master-web
      protocol: TCP
      name: loc-master-web
  selector:
    app: locust-master
  type: NodePort
