name: Tests

on: [push, pull_request]

permissions:
  contents: read

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - run: pip install -r requirements.txt

      - name: Lint
        run: python -m tox -e ruff

      - name: Mypy
        run: python -m tox -e mypy

  # lint_typecheck_webui:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: Set Node.js 20.x
  #       uses: actions/setup-node@v4
  #       with:
  #         node-version: 20.x
  #     - uses: borales/actions-yarn@v5
  #       with:
  #         cmd: webui:install
  #     - uses: borales/actions-yarn@v5
  #       with:
  #         cmd: webui:lint
  #     - uses: borales/actions-yarn@v5
  #       with:
  #         cmd: webui:type-check
