name: Tests

on: [push, pull_request]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: curl -LsSf https://astral.sh/uv/0.4.2/install.sh | sh
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - uses: borales/actions-yarn@v5
        with:
          cmd: install
          dir: locust_cloud/webui
      - run: uv venv
      - run: uv run ruff check
      - run: uv run mypy locust_cloud/
      - run: uvx --from build pyproject-build --wheel --installer uv
      - uses: actions/upload-artifact@v4
        with:
          name: dist-artifact
          path: dist/*
          
  lint_typecheck_webui:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - uses: borales/actions-yarn@v5
        with:
          cmd: install
          dir: locust_cloud/webui
      - uses: borales/actions-yarn@v5
        with:
          cmd: lint
          dir: locust_cloud/webui
      - uses: borales/actions-yarn@v5
        with:
          cmd: type-check
          dir: locust_cloud/webui  
    
  publish:
    name: Publish to PyPI
    needs: [build, lint_typecheck_webui]
    if: startsWith(github.event.ref, 'refs/tags')
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Download Python dist
        uses: actions/download-artifact@v4
        with:
          name: dist-artifact
          path: dist
      - uses: pypa/gh-action-pypi-publish@release/v1
