name: Tests

on: [push, pull_request]

permissions:
  contents: read

jobs:
  build_and_cache:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up uv
        run: curl -LsSf https://astral.sh/uv/0.4.2/install.sh | sh
      - run: uv venv
      - run: uv pip install .
      - name: Lint
        run: uv run ruff
      - name: Mypy
        run: uv run mypy
      - name: build
        run: uvx --from build pyproject-build --wheel --installer uv
      - name: Upload Python dist as Artifact
        uses: actions/upload-artifact@v4
        with:
          path: dist/*
          
  lint_typecheck_webui:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - uses: borales/actions-yarn@v5
        with:
          cmd: install
          dir: webui
      - uses: borales/actions-yarn@v5
        with:
          cmd: lint
          dir: webui
      - uses: borales/actions-yarn@v5
        with:
          cmd: type-check
          dir: webui
