name: Tests

on:
  push:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  AWS_ACCOUNT_ID: 637423602143
  AWS_REGION: eu-north-1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
      - uses: astral-sh/setup-uv@v2
      - uses: actions/setup-node@v4
        with:
          node-version: 22.x
      - run: uv venv --python 3.11
      - run: uv run ruff check
      - run: uv run ruff format --check
      - run: uv run pyright
      # any local changes would make hatch-vcs set a "local version" (+dev0...), so we ignore any uv.lock updates:
      - run: git update-index --assume-unchanged uv.lock
      - run: uv run locust-cloud --help
      - run: uvx --from build pyproject-build --wheel --installer uv
      - uses: actions/upload-artifact@v4
        with:
          name: dist-artifact
          path: dist/*

  publish_pypi:
    name: Publish to PyPI
    needs: [build]
    if: startsWith(github.event.ref, 'refs/tags')
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Download Python dist
        uses: actions/download-artifact@v4
        with:
          name: dist-artifact
          path: dist
      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
          skip-existing: true
